/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.CanhoDAO;
import DAO.ChitietGiaodichDAO;
import DAO.GiaodichDAO;
import DAO.KhachhangDAO;
import Model.Canho;
import Model.ChitietGiaodich;
import Model.Giaodich;
import Model.Khachhang;
import Model.Nhanvien;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.Common;

/**
 *
 * @author PTIT
 */
public class ThemGiaodich extends javax.swing.JFrame {

    /**
     * Creates new form ThemGiaodich
     */
    private KhachhangDAO khachhangDAO = new KhachhangDAO();
    private CanhoDAO canhoDAO = new CanhoDAO();
    private GiaodichDAO giaodichDAO = new GiaodichDAO();
    private ChitietGiaodichDAO chitietGiaodichDAO = new ChitietGiaodichDAO();
    private ArrayList<Khachhang> dsKH = new ArrayList<>();
    private ArrayList<Canho> dsCanho = new ArrayList<>();
    private Khachhang khachhang;
    private ArrayList<Canho> dsChitiet = new ArrayList<>();
    private QLMain qLMain;
    private short indexLoaiGD = 0;
    private int soluong = 0;
    private double tonggia = 0;

    public ThemGiaodich() {
        super("Thêm giao dịch");
        initComponents();

    }

    public void setqLMain(QLMain qLMain) {
        this.qLMain = qLMain;
    }

    public void loadTblSearchKH(String searchText) {
        dsKH = (ArrayList<Khachhang>) khachhangDAO.getAllByText(searchText);
        String[] title = {"Mã KH", "Tên KH", "CMND", "Ngày sinh"};
        DefaultTableModel model = new DefaultTableModel(null, title);
        for (int i = 0; i < dsKH.size(); i++) {
            model.addRow(dsKH.get(i).getObjSearch());
        }
        tblSearchKH.setModel(model);
    }

    public void loadTblSearchCH(String searchText) {
        dsCanho = (ArrayList<Canho>) canhoDAO.getAllByText(searchText);
        String[] title = {"Mã Căn hộ", "Tòa nhà", "Số nhà", "Giá bán", "Giá thuê"};
        DefaultTableModel model = new DefaultTableModel(null, title);
        for (int i = 0; i < dsCanho.size(); i++) {
            model.addRow(dsCanho.get(i).getObjSearch());
        }
        tblSearchCanho.setModel(model);
    }

    public boolean checkContains(Canho canho) {
        for (Canho ch : dsChitiet) {
            if (ch.getIdCanho() == canho.getIdCanho()) {
                return false;
            }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSearchKH = new javax.swing.JTextField();
        btnSearchKH = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchKH = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtSearchCanho = new javax.swing.JTextField();
        btnSearchCanho = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSearchCanho = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblChitietgiaodich = new javax.swing.JTable();
        btnThemKH = new javax.swing.JButton();
        btnChonCanho = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnThemGiaodich = new javax.swing.JButton();
        btnHuyGiaodich = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lbTenKH = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbCMND = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbGD = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        lbSoluong = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbTongsotien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Khách hàng");

        btnSearchKH.setText("Tìm kiếm");
        btnSearchKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchKHActionPerformed(evt);
            }
        });

        tblSearchKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã KH", "Tên KH", "CMND", "Ngày sinh"
            }
        ));
        jScrollPane1.setViewportView(tblSearchKH);

        jLabel2.setText("Căn hộ");

        btnSearchCanho.setText("Tìm kiếm");
        btnSearchCanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCanhoActionPerformed(evt);
            }
        });

        tblSearchCanho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Căn hộ", "Tòa nhà", "Số nhà", "Giá bán","Giá thuê"
            }
        ));
        jScrollPane2.setViewportView(tblSearchCanho);

        tblChitietgiaodich.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {"Mã Căn hộ", "Tên tòa nhà", "Số nhà", "Diện tích", "Số phòng", "Giá bán", "Giá thuê", "Mô tả","Trạng thái"}
        ));
        jScrollPane3.setViewportView(tblChitietgiaodich);

        btnThemKH.setText("Thêm thông tin khách hàng");
        btnThemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKHActionPerformed(evt);
            }
        });

        btnChonCanho.setText("Chọn căn hộ");
        btnChonCanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonCanhoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Chi tiết giao dịch");

        btnThemGiaodich.setText("Thực hiện giao dịch");
        btnThemGiaodich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemGiaodichActionPerformed(evt);
            }
        });

        btnHuyGiaodich.setText("Hủy giao dịch");
        btnHuyGiaodich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyGiaodichActionPerformed(evt);
            }
        });

        jLabel4.setText("Tên KH:");

        lbTenKH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setText("CMND:");

        lbCMND.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel6.setText("Loại giao dịch");

        cbGD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mua Căn hộ", "Cho thuê"}));
        cbGD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbGDItemStateChanged(evt);
            }
        });

        jLabel7.setText("Số lượng: ");

        lbSoluong.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        lbSoluong.setForeground(new java.awt.Color(255, 51, 0));

        jLabel9.setText("Tổng số tiền: ");

        lbTongsotien.setBackground(new java.awt.Color(255, 51, 51));
        lbTongsotien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTongsotien.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearchKH, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearchKH))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearchCanho, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearchCanho)
                                .addGap(0, 84, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThemKH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChonCanho)
                        .addGap(10, 10, 10))
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbGD, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(btnThemGiaodich)
                                .addGap(150, 150, 150)
                                .addComponent(btnHuyGiaodich))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbSoluong)
                                .addGap(162, 162, 162)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTongsotien)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchKH)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtSearchCanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCanho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemKH)
                    .addComponent(btnChonCanho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbTenKH)
                    .addComponent(jLabel5)
                    .addComponent(lbCMND))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbSoluong)
                    .addComponent(jLabel9)
                    .addComponent(lbTongsotien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemGiaodich)
                    .addComponent(btnHuyGiaodich)
                    .addComponent(jLabel6)
                    .addComponent(cbGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchKHActionPerformed
        // TODO add your handling code here:
        String searchText = txtSearchKH.getText();
        if (!searchText.equals("")) {
            loadTblSearchKH(searchText);
        } else {
            showMsg("Nhập từ khóa tìm kiếm");
        }
    }//GEN-LAST:event_btnSearchKHActionPerformed

    private void btnSearchCanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCanhoActionPerformed
        // TODO add your handling code here:
        String searchText = txtSearchCanho.getText();
        if (!searchText.equals("")) {
            loadTblSearchCH(searchText);
        } else {
            showMsg("Nhập từ khóa tìm kiếm");
        }
    }//GEN-LAST:event_btnSearchCanhoActionPerformed

    private void btnThemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKHActionPerformed
        // TODO add your handling code here:
        int selectRow = tblSearchKH.getSelectedRow();
        if (selectRow > -1) {
            khachhang = dsKH.get(selectRow);
            lbTenKH.setText(khachhang.getTenKhachhang().trim());
            lbCMND.setText(khachhang.getCmnd().trim());
            btnSearchKH.setEnabled(false);
        }
    }//GEN-LAST:event_btnThemKHActionPerformed

    private void btnChonCanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonCanhoActionPerformed
        // TODO add your handling code here:
        int selectRow = tblSearchCanho.getSelectedRow();
        if (selectRow > -1) {
            Canho canho = dsCanho.get(selectRow);
            if (checkContains(canho)) {
                dsChitiet.add(canho);
                loadDSChitiet(dsChitiet);
            } else {
                showMsg("Căn hộ đã có trong danh sách");
            }
        }
    }//GEN-LAST:event_btnChonCanhoActionPerformed

    private void btnThemGiaodichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemGiaodichActionPerformed
        // TODO add your handling code here:
        if (khachhang != null) {
            if (dsChitiet.size() > 0) {
                if (indexLoaiGD >= 0) {
                    try {
                        Giaodich giaodich = new Giaodich();
                        giaodich.setKhachhang(khachhang);
                        giaodich.setLoaiGiaodich(indexLoaiGD);
                        giaodich.setNhanvien(qLMain.getNhanvien());
                        giaodich.setSoluong(soluong);
                        giaodich.setTonggia(tonggia);
                        giaodich.setNgaylapGiaodich(new Date(new java.util.Date().getTime()));
                        ArrayList<ChitietGiaodich> dsChitietGiaodichs = new ArrayList<>();
                        giaodich = (Giaodich) giaodichDAO.add(giaodich);
                        for (Canho canho : dsChitiet) {
                            ChitietGiaodich chitietGiaodich = new ChitietGiaodich(giaodich, canho);
                            chitietGiaodichDAO.add(chitietGiaodich);
                            canho.setTrangthai((short) (indexLoaiGD+1));
                            canhoDAO.update(canho);
                        }
                        showMsg("Thêm giao dịch thành công");
                        removeNotify();
                        qLMain.loadTblChitietGD();
                    } catch (Exception ex) {
                        showMsg("Có lỗi xảy ra");
                    }
                } else {
                    showMsg("Chọn loại giao dịch");
                }
            } else {
                showMsg("Chọn ít nhất 1 căn hộ");
            }
        } else {
            showMsg("Thêm thông tin khách hàng");
        }
    }//GEN-LAST:event_btnThemGiaodichActionPerformed

    private void btnHuyGiaodichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyGiaodichActionPerformed
        // TODO add your handling code here:
        removeNotify();
    }//GEN-LAST:event_btnHuyGiaodichActionPerformed

    private void cbGDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbGDItemStateChanged
        // TODO add your handling code here:
        indexLoaiGD = (short) cbGD.getSelectedIndex();
        updateThongtin(indexLoaiGD);
        System.out.println("indexLoaiGD: "+indexLoaiGD);

    }//GEN-LAST:event_cbGDItemStateChanged
    public void showMsg(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemGiaodich.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemGiaodich.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemGiaodich.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemGiaodich.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ThemGiaodich().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonCanho;
    private javax.swing.JButton btnHuyGiaodich;
    private javax.swing.JButton btnSearchCanho;
    private javax.swing.JButton btnSearchKH;
    private javax.swing.JButton btnThemGiaodich;
    private javax.swing.JButton btnThemKH;
    private javax.swing.JComboBox<String> cbGD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbCMND;
    private javax.swing.JLabel lbSoluong;
    private javax.swing.JLabel lbTenKH;
    private javax.swing.JLabel lbTongsotien;
    private javax.swing.JTable tblChitietgiaodich;
    private javax.swing.JTable tblSearchCanho;
    private javax.swing.JTable tblSearchKH;
    private javax.swing.JTextField txtSearchCanho;
    private javax.swing.JTextField txtSearchKH;
    // End of variables declaration//GEN-END:variables

    private void loadDSChitiet(ArrayList<Canho> dsChitiet) {
        String[] title = {"Mã Căn hộ", "Tên tòa nhà", "Số nhà", "Diện tích", "Số phòng", "Giá bán", "Giá thuê", "Mô tả", "Trạng thái"};
        DefaultTableModel model = new DefaultTableModel(null, title);
        for (int i = 0; i < dsChitiet.size(); i++) {
            model.addRow(dsChitiet.get(i).getObj());
        }
        tblChitietgiaodich.setModel(model);
        updateThongtin(indexLoaiGD);
    }

    private void updateThongtin(int indexGD) {
        tonggia = 0;
        if (indexGD == 0) {
            for (Canho canho : dsChitiet) {
                tonggia += canho.getGiaban();
            }
        } else {
            for (Canho canho : dsChitiet) {
                tonggia += canho.getGiathue();
            }
        }
        soluong=dsChitiet.size();
        lbSoluong.setText(soluong+" Căn hộ");
        lbTongsotien.setText(Common.formatMoney(tonggia));
    }
}
